{% set name = "uharfbuzz" %}
{% set version = "0.44.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uharfbuzz-{{ version }}.tar.gz
  sha256: 3bc883f9b5d803f5ede08d1ad5b91dc1c768e9de902bc44e09468457c1c2e145

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cython
  host:
    - pip
    - python
    - setuptools-scm
    - cython
    - pkgconfig
  run:
    - python

test:
  imports:
    - uharfbuzz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trufont/uharfbuzz
  summary: Streamlined Cython bindings for the harfbuzz shaping engine
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
