{% set name = "uharfbuzz" %}
{% set version = "0.46.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uharfbuzz-{{ version }}.tar.gz
  sha256: b4ade2a584336227cc66e3db2e3947e4482dc37f643ac7719a616f8efd01488e

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cython
  host:
    - pip
    - python
    - setuptools-scm
    - cython
    - pkgconfig
    - setuptools
  run:
    - python

test:
  imports:
    - uharfbuzz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/trufont/uharfbuzz
  summary: Streamlined Cython bindings for the harfbuzz shaping engine
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
